version: "3.8"

services:
  object_service:
    container_name: object_service
    build: .
    ports:
      - "50050:50050"
    networks:
      consul-dc_mynet:
        ipv4_address: 172.20.0.10
    dns:
      - "172.20.0.5"
      - "8.8.8.8"
      - "8.8.8.4"

networks:
  consul-dc_mynet:
    external: true