version: "3.8"

services:
  object_service:
    container_name: object_service
    restart: unless-stopped
    build: .
    ports:
      - "50050:50050"
    networks:
      consul-dc_mynet:
        ipv4_address: 172.20.0.10
    dns:
      - "172.20.0.5"
      - "8.8.8.8"
      - "8.8.8.4"
    environment:
      POSTGRES_HOST: "${POSTGRES_HOST}"
      POSTGRES_DB: "${POSTGRES_DB}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_PORT: "${POSTGRES_PORT}"

  postgres_object:
    image: postgres:14.3
    container_name: postgres_object
    restart: unless-stopped
    environment:
      POSTGRES_DB: "${POSTGRES_DB}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    networks:
      - consul-dc_mynet
    volumes:
      - ~/docker_volumes/object_postgresql:/var/lib/postgresql/data
    ports:
      - "6543:5432"

networks:
  consul-dc_mynet:
    external: true